In [4]:
from torch.nn.utils.rnn import pad_sequence

In [5]:


# 定义数据：3个长度不同的序列
seq1 = torch.randint(1000,(10,))
seq2 = torch.randint(1000,(5,))
seq3 = torch.randint(1000,(13,))
print(seq1)
print(seq2)
print(seq3)



tensor([134,  64, 141, 387, 531, 901,  11, 519, 938,  17])
tensor([936,  19, 359, 364, 104])
tensor([245, 242, 534, 805, 298, 287, 835,  59, 636, 837, 575, 326, 942])


In [6]:
# 将三个数据合并成一个batch
seq_list = [seq1,seq2,seq3]
print(seq_list)

[tensor([134,  64, 141, 387, 531, 901,  11, 519, 938,  17]), tensor([936,  19, 359, 364, 104]), tensor([245, 242, 534, 805, 298, 287, 835,  59, 636, 837, 575, 326, 942])]


In [8]:
seq_batch = pad_sequence(seq_list)
print(seq_batch)
print(seq_batch.shape)

tensor([[134, 936, 245],
        [ 64,  19, 242],
        [141, 359, 534],
        [387, 364, 805],
        [531, 104, 298],
        [901,   0, 287],
        [ 11,   0, 835],
        [519,   0,  59],
        [938,   0, 636],
        [ 17,   0, 837],
        [  0,   0, 575],
        [  0,   0, 326],
        [  0,   0, 942]])
torch.Size([13, 3])
